<<<<<<< HEAD
name: Run Autograding Tests
=======
name: Auto Grading
>>>>>>> dc3cfd0296e773547e789db53c43981184f230d8

on:
  push:
    branches:
      - main

jobs:
  autograding:
<<<<<<< HEAD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        run: |
          python divisors.py
=======
    runs-on: ubuntu-latest  # GitHub Actions는 Ubuntu 환경에서 실행

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # 코드 체크아웃

      - name: Run Python script
        run: |
          python3 divisors.py  # divisors.py 파일을 실행하여 결과를 확인

      - name: Autograding
        run: |
          # 자동 채점 코드 추가 (필요한 경우)
          echo "Autograding completed"
>>>>>>> dc3cfd0296e773547e789db53c43981184f230d8
